### ISSUE TITLE
Integrating ListKit with Carthage fails

### ISSUE THREAD

**Issue by nikolasburk** [Ben-G/ListKit#6] opened 2016-11-12 19:16 UTC
I am trying to use `ListKit` with Carthage in a newly created project. This is what my **Cartfile** looked like at first:

    github "Ben-G/ListKit"

When running `carthage update --verbose`, I am getting the following output:

```
*** Fetching ListKit
*** Checking out ListKit at "1.0.0"
*** Building scheme "ListKit" in ListKit.xcodeproj
/usr/bin/xcrun xcodebuild -project /Users/nburk/Desktop/CarthageDemo/Carthage/Checkouts/ListKit/ListKit.xcodeproj -scheme ListKit -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos10.0

=== CLEAN TARGET ListKit OF PROJECT ListKit WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET ListKit OF PROJECT ListKit WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/nburk/Desktop/CarthageDemo/Carthage/Checkouts/ListKit/ListKit.xcodeproj -scheme ListKit -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
```

I then went to fork the project to [here](https://github.com/nikolasburk/ListKit), cloned it and then in Xcode used `Edit -> Convert -> To Current Swift Syntax` and pushed the changes back to the fork on my GitHub account.

Then I changed the **Cartfile** to 

    github "nikolasburk/ListKit"

to use my modified version. However, when I am running `carthage update --verbose`, I am still getting this error:

```
macbook-pro:CarthageDemo nburk$ carthage update
*** Fetching ListKit
*** Checking out ListKit at "1.0.0"
*** xcodebuild output can be found in /var/folders/n0/t0tg9zrd3ms5kd4bzpnz9dww0000gn/T/carthage-xcodebuild.65aeob.log
*** Building scheme "ListKit" in ListKit.xcodeproj
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/nburk/Desktop/CarthageDemo/Carthage/Checkouts/ListKit/ListKit.xcodeproj -scheme ListKit -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
```

Any idea what I can do to debug this further or how to fix the issue?

**Comment by nikolasburk** [comment] 2016-11-12 19:17
Also note, that the whole `ListKit` project builds properly on my machine when built from within Xcode rather than through Carthage.

**Comment by Ben-G** [comment] 2016-11-13 17:44
Hey @nikolasburk!

I believe the issue is, that you are still pointing to the `1.0.0` release, even after pointing to this repository in your `Cartfile`:

```
github "nikolasburk/ListKit"
```

If you only specify the repo, without specifying a branch or specific release, Carthage will pick the latest tag, which is still the Swift 2 version which was released as `1.0.0`.

You will need to pull in the specific branch on which you performed the conversion, i.e. `master`:

```
github "nikolasburk/ListKit" "master"
```

The real fix though will be creating a new release on this `ListKit` repo, once it's migrated to Swift 3.0.1 😃

**Comment by Ben-G** [comment] 2016-11-13 23:45
@nikolasburk I've just created a new release, `2.0.0` that has #8 merged. Thanks a lot for your help!

This should resolve your issue. Could you verify and report back? Thanks!

**Comment by nikolasburk** [comment] 2016-11-13 23:53
That's great, thanks so much! I can confirm that the project now builds when fetching the latest release.

<img width="438" alt="screen shot 2016-11-13 at 15 53 06" src="https://cloud.githubusercontent.com/assets/4058327/20249930/5825d750-a9b9-11e6-9541-ab2d9e82b345.png">

**Closed as completed** 2016-11-13 23:54 UTC
